# Favorite
## Get favorite list
GET http://localhost:3000/offers/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NGE5NjE2ZTZiYmI2Njc5ZWZlZjMzMyIsImlhdCI6MTY5OTQ3NjU5OSwiZXhwIjoxNjk5NjQ5Mzk5fQ.9Az-Lfsuoxb022zSO_2Yepgh3R7v6Mp8nxo8hvIGh-o

###

## Add offer to favorite
POST http://localhost:3000/offers/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NGE5NjE2ZTZiYmI2Njc5ZWZlZjMzMyIsImlhdCI6MTY5OTQ3NzA2MSwiZXhwIjoxNjk5NjQ5ODYxfQ.CuBJinmtH2d8v6KMyN8M07Kzk2oo6AC9GA6VMheK9Yg

{
  "offerId": "653e7031065fdb177223aea4"
}

###

## Delete offer from favorite
DELETE http://localhost:3000/offers/favorite/65354a7a6626eeefa84e9ff2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDdiNDA2MmM1NWVhZDI5MTRiOTdkNCIsImVtYWlsIjoibWFyZWV2MjMyMUBnbWFpbC5jb20iLCJuYW1lIjoiUGF2ZWwgTWFyZWV2IiwiaWF0IjoxNjk5MjEwMDQzLCJleHAiOjE2OTkyMTM2NDN9.4KExO3awBsXO_dJ-LEeWgEFHeZVhRgB2i53Mnl7Lx7A
