# Users
## Signup
POST http://localhost:3000/users/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Pavel Mareev",
  "email": "mareev1@gmail.com",
  "type": "default",
  "password": "secret_01234",
  "avatar": "my-avatard.uk/felix.jpg"
}

###

## Login
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "mareev2321@gmail.com",
  "password": "secret_01234"
}

###

## Send avatar

POST http://localhost:3000/users/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDdiNDA2MmM1NWVhZDI5MTRiOTdkNCIsImVtYWlsIjoibWFyZWV2MjMyMUBnbWFpbC5jb20iLCJuYW1lIjoiUGF2ZWwgTWFyZWV2IiwiaWF0IjoxNjk5MjAzMTAwLCJleHAiOjE2OTkyMDY3MDB9.B9TULjK0Y5KFJoCsKHIxKx5ZivoXKx3dt__cjriet1o

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="983.jpg"
Content-Type: image/jpeg

< /Users/etpotato/Downloads/983.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
