# Offers
## Get offers list
GET http://localhost:3000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NGE5NjE2ZTZiYmI2Njc5ZWZlZjMzMyIsImlhdCI6MTY5OTQ3NzA2MSwiZXhwIjoxNjk5NjQ5ODYxfQ.CuBJinmtH2d8v6KMyN8M07Kzk2oo6AC9GA6VMheK9Yg
###

## Get offer by id
GET http://localhost:3000/offers/6547b51a66a3743d14a182a1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDdiNDA2MmM1NWVhZDI5MTRiOTdkNCIsImVtYWlsIjoibWFyZWV2MjMyMUBnbWFpbC5jb20iLCJuYW1lIjoiUGF2ZWwgTWFyZWV2IiwiaWF0IjoxNjk5MjEwMDQzLCJleHAiOjE2OTkyMTM2NDN9.4KExO3awBsXO_dJ-LEeWgEFHeZVhRgB2i53Mnl7Lx7A
###

## Create offer
POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDdiNDA2MmM1NWVhZDI5MTRiOTdkNCIsImVtYWlsIjoibWFyZWV2MjMyMUBnbWFpbC5jb20iLCJuYW1lIjoiUGF2ZWwgTWFyZWV2IiwiaWF0IjoxNjk5MTk4MjE2LCJleHAiOjE2OTkyMDE4MTZ9.BawBdMsN_J3uAsPyJ_X_Xo2HuuMTAlZzYmCjianWYM4

{
  "title": "Luxury Downtown Studio",
  "description": "Indulge in city living at its finest with this modern studio apartment. Enjoy breathtaking city views.",
  "city": "Paris",
  "preview": "https://picsum.photos/200",
  "photos": [
    "https://picsum.photos/800/480",
    "https://picsum.photos/1200/800",
    "https://picsum.photos/600/400",
    "https://picsum.photos/800/1200",
    "https://picsum.photos/400/480",
    "https://picsum.photos/1125/366"
  ],
  "isPremium": false,
  "housingType": "house",
  "roomCount": 3,
  "tenantCount": 2,
  "price": 100,
  "features": [
    "Breakfast",
    "Air conditioning",
    "Laptop friendly workspace"
  ],
  "location": [
    48.85661,
    2.351499
  ]
}

###

## Update offer
PATCH http://localhost:3000/offers/6547bcfa05b1285ed59d16cc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDdiNDA2MmM1NWVhZDI5MTRiOTdkNCIsImVtYWlsIjoibWFyZWV2MjMyMUBnbWFpbC5jb20iLCJuYW1lIjoiUGF2ZWwgTWFyZWV2IiwiaWF0IjoxNjk5MTk4MjE2LCJleHAiOjE2OTkyMDE4MTZ9.BawBdMsN_J3uAsPyJ_X_Xo2HuuMTAlZzYmCjianWYM4

{
  "housingType": "apartment"
}

###

## Delete offer
DELETE http://localhost:3000/offers/6547bcfa05b1285ed59d16cc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDdiNDA2MmM1NWVhZDI5MTRiOTdkNCIsImVtYWlsIjoibWFyZWV2MjMyMUBnbWFpbC5jb20iLCJuYW1lIjoiUGF2ZWwgTWFyZWV2IiwiaWF0IjoxNjk5MTk4MjE2LCJleHAiOjE2OTkyMDE4MTZ9.BawBdMsN_J3uAsPyJ_X_Xo2HuuMTAlZzYmCjianWYM4

###

## Get premium offers for the city
GET http://localhost:3000/offers/premium/Paris HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDdiNDA2MmM1NWVhZDI5MTRiOTdkNCIsImVtYWlsIjoibWFyZWV2MjMyMUBnbWFpbC5jb20iLCJuYW1lIjoiUGF2ZWwgTWFyZWV2IiwiaWF0IjoxNjk5MjE0OTYwLCJleHAiOjE2OTkzODc3NjB9.UyWF0mGzfGAIOCrwWSaVL4_krkUf0miOu_dNZ48Z_dw
